"""add vitals and medicine timing

Revision ID: 024b33cb0284
Revises: f23f606fa3e8
Create Date: 2026-08-07 20:58:54.287101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '024b33cb0284'
down_revision: Union[str, None] = 'f23f606fa3e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicines', sa.Column('timing', sa.String(length=50), nullable=True))
    op.add_column('medicines', sa.Column('timing_hi', sa.String(length=50), nullable=True))
    op.add_column('prescriptions', sa.Column('temperature', sa.String(length=50), nullable=True))
    op.add_column('prescriptions', sa.Column('blood_pressure', sa.String(length=50), nullable=True))
    op.add_column('prescriptions', sa.Column('pulse', sa.String(length=50), nullable=True))
    op.add_column('prescriptions', sa.Column('weight', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions', 'weight')
    op.drop_column('prescriptions', 'pulse')
    op.drop_column('prescriptions', 'blood_pressure')
    op.drop_column('prescriptions', 'temperature')
    op.drop_column('medicines', 'timing_hi')
    op.drop_column('medicines', 'timing')
    # ### end Alembic commands ###
