"""add hindi translation fields

Revision ID: 0bf9aab0a993
Revises: 3c3c37fbce9e
Create Date: 2026-08-07 20:42:36.841510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0bf9aab0a993'
down_revision: Union[str, None] = '3c3c37fbce9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicines', sa.Column('frequency_hi', sa.String(length=150), nullable=True))
    op.add_column('medicines', sa.Column('duration_hi', sa.String(length=150), nullable=True))
    op.add_column('prescriptions', sa.Column('chief_complaint_hi', sa.Text(), nullable=True))
    op.add_column('prescriptions', sa.Column('diagnosis_hi', sa.Text(), nullable=True))
    op.add_column('prescriptions', sa.Column('advice_hi', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions', 'advice_hi')
    op.drop_column('prescriptions', 'diagnosis_hi')
    op.drop_column('prescriptions', 'chief_complaint_hi')
    op.drop_column('medicines', 'duration_hi')
    op.drop_column('medicines', 'frequency_hi')
    # ### end Alembic commands ###
