"""add medicine timing_when fields

Revision ID: 15b1bc2ba91b
Revises: 608e2b6d6201
Create Date: 2026-08-08 14:02:45.830023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '15b1bc2ba91b'
down_revision: Union[str, None] = '608e2b6d6201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicines', sa.Column('timing_when', sa.String(length=50), nullable=True))
    op.add_column('medicines', sa.Column('timing_when_hi', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicines', 'timing_when_hi')
    op.drop_column('medicines', 'timing_when')
    # ### end Alembic commands ###
