"""remove claim codes, make patient phone unique

Revision ID: 23b6313f606e
Revises: 66e762eeef58
Create Date: 2026-08-10 00:32:37.008328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '23b6313f606e'
down_revision: Union[str, None] = '66e762eeef58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caregivers', 'claim_code')
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=True)
    op.drop_column('patients', 'claim_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('claim_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.add_column('caregivers', sa.Column('claim_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
