"""move allergies from patient profile to per-prescription field

Revision ID: 401d37ebc874
Revises: 23b6313f606e
Create Date: 2026-08-10 01:15:45.049557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '401d37ebc874'
down_revision: Union[str, None] = '23b6313f606e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'known_allergies')
    op.add_column('prescriptions', sa.Column('allergies', sa.Text(), nullable=True))
    op.add_column('prescriptions', sa.Column('allergies_hi', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions', 'allergies_hi')
    op.drop_column('prescriptions', 'allergies')
    op.add_column('patients', sa.Column('known_allergies', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
