"""add known allergies field

Revision ID: 608e2b6d6201
Revises: 70051b4eba9b
Create Date: 2026-08-07 23:35:32.300415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '608e2b6d6201'
down_revision: Union[str, None] = '70051b4eba9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('known_allergies', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'known_allergies')
    # ### end Alembic commands ###
