"""add consultation deletion audit log

Revision ID: 66e762eeef58
Revises: a2dd1f7d98b7
Create Date: 2026-08-09 13:30:34.079454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '66e762eeef58'
down_revision: Union[str, None] = 'a2dd1f7d98b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_deletion_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('consultation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('doctor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('status_at_deletion', sa.String(length=50), nullable=False),
    sa.Column('had_transcript', sa.Boolean(), nullable=False),
    sa.Column('had_draft_prescription', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultation_deletion_logs')
    # ### end Alembic commands ###
