"""add diet advice field

Revision ID: 70051b4eba9b
Revises: 8f3cf9d84053
Create Date: 2026-08-07 23:19:20.191343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '70051b4eba9b'
down_revision: Union[str, None] = '8f3cf9d84053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions', sa.Column('diet_advice', sa.Text(), nullable=True))
    op.add_column('prescriptions', sa.Column('diet_advice_hi', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions', 'diet_advice_hi')
    op.drop_column('prescriptions', 'diet_advice')
    # ### end Alembic commands ###
