"""add caregivers and prescription audio

Revision ID: 8f3cf9d84053
Revises: 024b33cb0284
Create Date: 2026-08-07 22:51:00.352937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8f3cf9d84053'
down_revision: Union[str, None] = '024b33cb0284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregivers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caregivers_email'), 'caregivers', ['email'], unique=True)
    op.create_table('caregiver_patient_links',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('caregiver_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('relationship_label', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregivers.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caregiver_id', 'patient_id', name='uq_caregiver_patient')
    )
    op.create_table('prescription_audio',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('prescription_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('audio_data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prescription_id', 'lang', name='uq_prescription_audio_lang')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescription_audio')
    op.drop_table('caregiver_patient_links')
    op.drop_index(op.f('ix_caregivers_email'), table_name='caregivers')
    op.drop_table('caregivers')
    # ### end Alembic commands ###
