"""add claim_code to patients and caregivers

Revision ID: a2dd1f7d98b7
Revises: af6d10fb004b
Create Date: 2026-08-09 13:00:51.861009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a2dd1f7d98b7'
down_revision: Union[str, None] = 'af6d10fb004b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caregivers', sa.Column('claim_code', sa.String(length=10), nullable=True))
    op.add_column('patients', sa.Column('claim_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'claim_code')
    op.drop_column('caregivers', 'claim_code')
    # ### end Alembic commands ###
