"""add medicine duration_inferred flag

Revision ID: af6d10fb004b
Revises: 15b1bc2ba91b
Create Date: 2026-08-08 22:03:49.298438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'af6d10fb004b'
down_revision: Union[str, None] = '15b1bc2ba91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'medicines', sa.Column('duration_inferred', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicines', 'duration_inferred')
    # ### end Alembic commands ###
