"""add tests table

Revision ID: f23f606fa3e8
Revises: 0bf9aab0a993
Create Date: 2026-08-07 20:53:14.944815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f23f606fa3e8'
down_revision: Union[str, None] = '0bf9aab0a993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('prescription_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('instructions', sa.String(length=255), nullable=True),
    sa.Column('instructions_hi', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    # ### end Alembic commands ###
